# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  model: Conformer
  in_chan: 64
  n_src: 2
  out_chan: 64
  n_blocks: 16
  aheads: 4
  adims: 256
  eunits: 1024
  chunk_size: 256
  hop_size: 64
  mask_act: 'sigmoid'
  dropout: 0
# Training config
training:
  epochs: 100
  batch_size: 
  num_workers: 8
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.0001
  weight_decay: !!float 1e-2
# Data config
data:
  train_dir: data/wav16k/min/tr/
  valid_dir: data/wav16k/min/cv/
  task: sep_noisy
  nondefault_nsrc:
  sample_rate: 16000
  mode: min
  segment: 2.0
